# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScAction',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScAns',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('ad', models.CharField(blank=True, max_length=20, null=True)),
                ('soyad', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('parent_username', models.CharField(blank=True, max_length=2000, null=True)),
                ('notif_ask', models.CharField(blank=True, max_length=3, null=True)),
                ('notif_answer', models.CharField(blank=True, max_length=3, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_tel_num', models.CharField(blank=True, max_length=30, null=True)),
                ('mob_tel_num', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('ata_adi', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_ans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScAnsAction',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('user_id', models.FloatField()),
                ('action_id', models.FloatField()),
                ('req_id', models.FloatField()),
                ('a_date', models.DateField()),
            ],
            options={
                'db_table': 'sc_ans_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScAnsActionNotif',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('user_id', models.FloatField(blank=True, null=True)),
                ('action_id', models.FloatField(blank=True, null=True)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('who_see', models.CharField(blank=True, max_length=50, null=True)),
                ('notif', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_ans_action_notif',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScAnsCategories',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('ans_username', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_id', models.FloatField(blank=True, null=True)),
                ('utype', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'sc_ans_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScAnsParent',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sc_ans_parent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScCategories',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sc_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScComments',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('ans_id', models.FloatField(blank=True, max_length=200, null=True)),
                ('ins_date', models.CharField(blank=True, max_length=40, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('comment_text', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'sc_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScComments2',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('ans_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ins_date', models.CharField(blank=True, max_length=40, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('comment_text', models.TextField(blank=True, null=True)),
                ('comment_text2', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'sc_comments2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScCommentsPrivacy',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('comment_id', models.FloatField(blank=True, null=True)),
                ('ans_id', models.CharField(blank=True, max_length=200, null=True)),
                ('com_act', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_comments_privacy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScLogs',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('logtype', models.CharField(blank=True, max_length=200, null=True)),
                ('logdate', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'sc_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScNotifyList',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.CharField(blank=True, max_length=200, null=True)),
                ('notify', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_notify_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScRequests',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('rtype', models.CharField(blank=True, max_length=100, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('solution_desc', models.CharField(blank=True, max_length=4000, null=True)),
                ('ans_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('ins_date', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sc_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScRequestsCategories',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('cat_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_requests_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScRequestTags',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('tagged_user', models.CharField(blank=True, max_length=50, null=True)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('view_status', models.CharField(blank=True, max_length=30, null=True)),
                ('tagged_date', models.CharField(blank=True, max_length=20, null=True)),
                ('who_tagged', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sc_request_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScSubCategories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('slug', models.CharField(max_length=150)),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sc_sub_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaCats',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('req_same', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'scta_cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaCommentNotif',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('comment_id', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('req_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scta_comment_notif',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaComments',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('ans_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ins_date', models.CharField(blank=True, max_length=40, null=True)),
                ('file_path', models.CharField(blank=True, max_length=2000, null=True)),
                ('comment_text', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'scta_comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaLogs',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('logtype', models.CharField(blank=True, max_length=200, null=True)),
                ('logdate', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'scta_logs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaTasks',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('rtype', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('ans_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('ins_date', models.CharField(blank=True, max_length=40, null=True)),
                ('sol_date', models.CharField(blank=True, max_length=40, null=True)),
                ('ttype', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('req_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'scta_tasks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaTasksCats',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('req_id', models.FloatField(blank=True, null=True)),
                ('cat_id', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scta_tasks_cats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaTips',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'scta_tips',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaUsers',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('ad', models.CharField(blank=True, max_length=20, null=True)),
                ('soyad', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.FloatField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=2000, null=True)),
                ('notif_ask', models.CharField(blank=True, max_length=3, null=True)),
                ('notif_answer', models.CharField(blank=True, max_length=3, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('internal_tel_num', models.CharField(blank=True, max_length=30, null=True)),
                ('mob_tel_num', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('ata_adi', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_username', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'scta_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SctaUsersCats',
            fields=[
                ('id', models.FloatField(blank=True, null=True, primary_key=True, serialize=False)),
                ('ans_username', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_id', models.FloatField(blank=True, null=True)),
                ('utype', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'scta_users_cats',
                'managed': True,
            },
        ),
    ]
