# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScComments',
            new_name='ScComment',
        ),
    ]
