# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_scans_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sccomments',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
