# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20170116_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='request_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
