# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 05:59
from __future__ import unicode_literals

import database.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0007_auto_20170116_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=database.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
