# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20170117_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sccomments',
            name='req_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
