# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20170117_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScActionNotif',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('action_id', models.FloatField(blank=True, null=True)),
                ('user_id', models.FloatField(blank=True, null=True)),
                ('notif', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sc_action_notif',
                'managed': True,
            },
        ),
    ]
