# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_scansactionnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansactionnew',
            name='action_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scansactionnew',
            name='req_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scansactionnew',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
