# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20170124_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scactionnotif',
            name='action_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scactionnotif',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
