# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20170126_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screquestsnew',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='solution_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
