# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20170126_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screquestsnew',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='file_path',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='ins_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='rtype',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='sender',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='screquestsnew',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
