# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20170126_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScRequestsNew',
        ),
    ]
