# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_delete_screquestsnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
