# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20161115_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, default='Message', max_length=120, null=True)),
            ],
        ),
    ]
