# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20161208_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
