# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20161212_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='ScAns',
        ),
    ]
