# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20161212_0650'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scans',
            table='ScAns',
        ),
    ]
