# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20161212_0652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScAns',
            new_name='profile',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
