# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20161212_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.FloatField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, db_column='IP', max_length=20, null=True),
        ),
    ]
