# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20161212_0722'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='ScAns',
        ),
    ]
