# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20161212_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
