# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20161212_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ata_adi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='internal_tel_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mob_tel_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notif_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notif_ask',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='parent_username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='soyad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='asdas', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
