# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 11:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0030_auto_20161212_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Sc_Ans',
        ),
    ]
