# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20161212_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ad',
            field=models.CharField(blank=True, default='sdf', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ata_adi',
            field=models.CharField(blank=True, default='sdf', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='sdf', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, default='sdf', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, default='sdf', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='internal_tel_num',
            field=models.CharField(blank=True, default='sdf', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, default='sdf', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob_tel_num',
            field=models.CharField(blank=True, default='sdf', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notif_answer',
            field=models.CharField(blank=True, default='sdf', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notif_ask',
            field=models.CharField(blank=True, default='sdf', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parent_username',
            field=models.CharField(blank=True, default='sdf', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, default='sdf', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='sdf', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.FloatField(blank=True, default='sdf', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='soyad',
            field=models.CharField(blank=True, default='sdf', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, default='sdf', max_length=200, null=True),
        ),
    ]
