# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_auto_20161212_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
