# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20161219_0646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestUsers',
            new_name='RequestUsersProfile',
        ),
    ]
