# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0041_auto_20161219_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user that authenticates')),
            ],
            options={
                'verbose_name': 'IP Access',
                'verbose_name_plural': 'IP Accesses',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, default='department', max_length=120, null=True),
        ),
    ]
