# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20161227_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaccess',
            name='user',
        ),
        migrations.DeleteModel(
            name='IPAccess',
        ),
    ]
